spring:
  messages:
    basename: messages,errors
  mail:
    host: smtp.gmail.com
    port: 587
    username: hansungmoon1002@gmail.com
    password: fklqiririikcrfxd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  #  profiles:
  #    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/neighbor
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #        QueryDSL로 사용된 JPQL 보기
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
